Fix build by adding missing cstdint include
Tested with gcc (GCC) 13.2.1 20230801.

Fixed error was:
error: ‘uint32_t’ does not name a type

note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?