Fix build by adding missing cstdint include (#240)
Tested with gcc (GCC) 13.2.1 20230801.

Fixed error was:
error: ‘uint32_t’ does not name a type